# yamllint configuration
---
extends: default

rules:
  line-length:
    max: 220
    level: warning

  indentation:
    spaces: 2
    indent-sequences: true

  comments: disable

  # Allow duplicate keys (useful for docker-compose overrides)
  key-duplicates: disable

  # Allow document start markers to be optional
  document-start: disable

  # Be more lenient with truthy values (yes/no, on/off, etc.)
  truthy:
    allowed-values: ["true", "false", "yes", "no", "on", "off"]
    check-keys: false

ignore: |
  terraform/.terraform/
  node_modules/
  .git/
